#!/usr/bin/env python3
"""Generate manuscript macros and non-primary tables from verified JSON."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


def load(path: str) -> dict:
    return json.loads((ROOT / path).read_text(encoding="utf-8"))


def pct(value: float, digits: int = 1) -> str:
    return f"{100 * value:.{digits}f}"


def tex_label(value: str) -> str:
    return value.replace("_", r"\_")


def main() -> int:
    representation = load("paper/data/representation_audit.json")
    heldout = load("paper/data/heldout_0813_summary.json")
    negative = load("paper/data/negative_results.json")
    ablation = load("paper/data/ablation/summary.json")

    corpus = representation["corpus"]
    disagreement = representation["head_disagreement"]
    head_approval = representation["team_holdout_expert_agreement"]["overall"]
    replay_approval = heldout["overall"]
    contrasts = {row["contrast"]: row for row in ablation["contrasts"]}
    interaction = ablation["interaction"]
    negatives = {row["experiment"]: row for row in negative["results"]}

    macros = ["% Auto-generated by paper/scripts/generate_tables.py; do not edit."]
    values = {
        "CorpusDecisions": f"{corpus['decisions']:,}",
        "OrdinaryPlayOptions": f"{corpus['ordinary_play_options']:,}",
        "MultiIdentityStates": f"{corpus['states_with_two_or_more_play_identities']:,}",
        "MultiIdentityStatePct": pct(corpus["multi_identity_proportion_of_play_states"]),
        "CollisionGroups": str(corpus["blind_signature_collision_groups"]),
        "CollisionInstancePct": pct(corpus["collision_instance_proportion"]),
        "AllHeadDisagreementPct": pct(disagreement["all"]["rate"]),
        "MultiHeadDisagreementPct": pct(disagreement["multi_play_identity"]["rate"]),
        "OtherHeadDisagreementPct": pct(disagreement["other"]["rate"]),
        "HeadHoldoutApproval": f"{head_approval['approval']:.3f}",
        "HeadHoldoutCILow": f"{head_approval['episode_bootstrap_95_ci'][0]:.3f}",
        "HeadHoldoutCIHigh": f"{head_approval['episode_bootstrap_95_ci'][1]:.3f}",
        "HeadHoldoutDecisive": f"{head_approval['decisive']:,}",
        "ReplayApproval": f"{replay_approval['approval']:.3f}",
        "ReplayApprovalCILow": f"{replay_approval['episode_bootstrap_95_ci'][0]:.3f}",
        "ReplayApprovalCIHigh": f"{replay_approval['episode_bootstrap_95_ci'][1]:.3f}",
        "ReplayApprovalDecisive": f"{replay_approval['binary_decisive']:,}",
        "ReplayApprovalDisagreements": f"{replay_approval['disagreements']:,}",
        "ReplayApprovalAbstain": f"{replay_approval['abstain']:,}",
        "AblationEncoderOnlyPP": pct(contrasts["C2-C1"]["effect"], 2),
        "AblationBlindTrainingPP": pct(contrasts["C3-C1"]["effect"], 2),
        "AblationIdentityTrainingPP": pct(contrasts["C4-C2"]["effect"], 2),
        "AblationPostTrainingEncoderPP": pct(contrasts["C4-C3"]["effect"], 2),
        "AblationInteractionPP": pct(interaction["effect"], 2),
        "TemporalEffectPP": pct(negatives["temporal_two_turn_takeover"]["effect"], 3),
        "SequenceEffectPP": pct(negatives["bounded_sequence_oracle"]["effect"], 3),
    }
    for name, value in values.items():
        macros.append(f"\\newcommand{{\\{name}}}{{{value}}}")
    (ROOT / "paper/diagnostic_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")

    tables = ROOT / "paper/tables"
    tables.mkdir(parents=True, exist_ok=True)
    representation_lines = [
        "% Auto-generated by paper/scripts/generate_tables.py; do not edit.",
        r"\begin{table}",
        r"\caption{Representation and head-only diagnostics on retained feature rows. These are not gameplay outcomes.}",
        r"\label{tab:representation}",
        r"\begin{ruledtabular}",
        r"\begin{tabular}{lr}",
        r"Diagnostic & Value \\",
        r"\hline",
        f"Decisions & {corpus['decisions']:,} \\\\ ",
        f"Ordinary PLAY options & {corpus['ordinary_play_options']:,} \\\\ ",
        f"Blind unresolved / repaired bound & {corpus['baseline_unresolved_play_options']:,} / {corpus['identity_bound_play_options']:,} \\\\ ",
        f"Multi-identity PLAY states & {corpus['states_with_two_or_more_play_identities']:,} ({pct(corpus['multi_identity_proportion_of_play_states'])}\\%) \\\\ ",
        f"Head disagreement, multi-identity & {pct(disagreement['multi_play_identity']['rate'])}\\% \\\\ ",
        f"Head disagreement, other & {pct(disagreement['other']['rate'])}\\% \\\\ ",
        r"\end{tabular}", r"\end{ruledtabular}", r"\end{table}", "",
    ]
    (tables / "representation.tex").write_text("\n".join(representation_lines), encoding="utf-8")

    ablation_lines = [
        "% Auto-generated by paper/scripts/generate_tables.py; do not edit.",
        r"\begin{table*}",
        r"\caption{Matched four-cell ablation contrasts over 2,800 common worlds. Effects are percentage-point win differences; intervals use the preregistered paired within-cell bootstrap.}",
        r"\label{tab:ablation}",
        r"\begin{ruledtabular}",
        r"\begin{tabular}{lrrrr}",
        r"Contrast & Effect & 95\% CI & Discordant & Holm $p$ \\",
        r"\hline",
    ]
    for result in ablation["contrasts"]:
        ablation_lines.append(
            f"{result['contrast']} & {100 * result['effect']:+.2f} & "
            f"[{100 * result['ci_low']:+.2f}, {100 * result['ci_high']:+.2f}] & "
            f"{result['left_only_wins']}/{result['right_only_wins']} & "
            f"{result['holm_adjusted_p_5_contrasts']:.3f} \\\\"
        )
    ablation_lines.append(
        f"Interaction & {100 * interaction['effect']:+.2f} & "
        f"[{100 * interaction['ci_low']:+.2f}, {100 * interaction['ci_high']:+.2f}] & -- & -- \\\\"
    )
    ablation_lines.extend([r"\end{tabular}", r"\end{ruledtabular}", r"\end{table*}", ""])
    (tables / "ablation.tex").write_text("\n".join(ablation_lines), encoding="utf-8")

    heldout_lines = [
        "% Auto-generated by paper/scripts/generate_tables.py; do not edit.",
        r"\begin{table}",
        r"\caption{Expert-action agreement conditional on EXP23--C0 semantic disagreement in retained 2026-08-13 replay units. Abstentions are excluded from the approval denominator.}",
        r"\label{tab:heldout}",
        r"\begin{ruledtabular}",
        r"\begin{tabular}{lrrrr}",
        r"Stratum & EXP23 & C0 & Abstain & Approval \\",
        r"\hline",
    ]
    heldout_groups = [("Overall", heldout["overall"])] + [
        (name.replace("_", " "), value) for name, value in sorted(heldout["by_identity_state"].items())
    ]
    for label, result in heldout_groups:
        heldout_lines.append(
            f"{tex_label(label)} & {result['candidate_approved']} & {result['control_approved']} & "
            f"{result['abstain']} & {result['approval']:.3f} \\\\"
        )
    heldout_lines.extend([r"\end{tabular}", r"\end{ruledtabular}", r"\end{table}", ""])
    (tables / "heldout.tex").write_text("\n".join(heldout_lines), encoding="utf-8")

    negative_lines = [
        "% Auto-generated by paper/scripts/generate_tables.py; do not edit.",
        r"\begin{table}",
        r"\caption{Independently reaggregated null results with surviving raw artifacts.}",
        r"\label{tab:negative}",
        r"\begin{ruledtabular}",
        r"\begin{tabular}{lrrr}",
        r"Experiment & Units & Effect & 95\% CI \\",
        r"\hline",
    ]
    for result in negative["results"]:
        negative_lines.append(
            f"{tex_label(result['label'])} & {result['n']:,} & {100 * result['effect']:+.3f} & "
            f"[{100 * result['ci_low']:+.3f}, {100 * result['ci_high']:+.3f}] \\\\"
        )
    negative_lines.extend([r"\end{tabular}", r"\end{ruledtabular}", r"\end{table}", ""])
    (tables / "negative.tex").write_text("\n".join(negative_lines), encoding="utf-8")
    print(json.dumps({"macros": len(values), "tables": 4}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
