#!/usr/bin/env python3
"""Generate manuscript macros and all five tables from verified JSON."""

from __future__ import annotations

import json
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
IS_RELEASE = (SCRIPT_DIR.parent / "data/processed").is_dir()
ROOT = SCRIPT_DIR.parent if IS_RELEASE else Path(__file__).resolve().parents[2]
DATA = ROOT / "data/processed" if IS_RELEASE else ROOT / "paper/data"
OUTPUT = ROOT / "generated" if IS_RELEASE else ROOT / "paper"


def load(path: str) -> dict:
    return json.loads((DATA / path).read_text(encoding="utf-8"))


def pct(value: float, digits: int = 1) -> str:
    return f"{100 * value:.{digits}f}"


def tex_label(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$",
        "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}",
        "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in value)


def main() -> int:
    representation = load("representation_audit.json")
    heldout = load("heldout_0813_summary.json")
    negative = load("negative_results.json")
    ablation = load("ablation_summary.json" if IS_RELEASE else "ablation/summary.json")
    stats = load("statistical_summary.json")

    corpus = representation["corpus"]
    disagreement = representation["head_disagreement"]
    head_approval = representation["refresh_holdout_recorded_action_agreement"]["overall"]
    replay_approval = heldout["overall"]
    if ablation.get("schema_version") != 2 or ablation.get("status") != "INVALIDATED":
        raise ValueError("ablation summary must preserve the invalidated schema-2 result")
    within_ablation = {
        row["contrast"]: row for row in ablation["within_run_descriptive"]["contrasts"]
    }
    exploratory_ablation = {
        row["contrast"]: row
        for row in ablation["exploratory_reproducible_control_subset"]["contrasts"]
    }
    exploratory_interaction = ablation["exploratory_reproducible_control_subset"]["interaction"]
    parity = ablation["control_parity_audit"]
    negatives = {row["experiment"]: row for row in negative["results"]}

    macros = ["% Auto-generated by paper/scripts/generate_tables.py; do not edit."]
    values = {
        "CorpusDecisions": f"{corpus['decisions']:,}",
        "OrdinaryPlayOptions": f"{corpus['ordinary_play_options']:,}",
        "UnresolvedPlayOptions": f"{corpus['baseline_unresolved_play_options']:,}",
        "UnresolvedPlayPct": pct(corpus["baseline_unresolved_proportion"]),
        "PlayStates": f"{corpus['states_with_play']:,}",
        "MultiPlayOptionStates": f"{corpus['states_with_two_or_more_play_options']:,}",
        "UniqueIndexMultiPlayStates": f"{corpus['multi_play_option_states_with_unique_hand_indices']:,}",
        "IndexMatchedPlayOptions": f"{corpus['play_options_with_numeric_index_matching_raw']:,}",
        "MultiIdentityStates": f"{corpus['states_with_two_or_more_play_identities']:,}",
        "MultiIdentityStatePct": pct(corpus["multi_identity_proportion_of_play_states"]),
        "ExactCollisionGroups": str(corpus["within_state_cross_identity_collision_groups"]),
        "ExactCollisionStates": str(corpus["states_with_within_state_cross_identity_collision"]),
        "ExactCollisionInstancePct": pct(
            corpus["within_state_cross_identity_collision_instance_proportion"]
        ),
        "AllHeadDisagreementPct": pct(disagreement["all"]["rate"]),
        "MultiHeadDisagreementPct": pct(disagreement["multi_play_identity"]["rate"]),
        "OtherHeadDisagreementPct": pct(disagreement["other"]["rate"]),
        "HeadHoldoutApproval": f"{head_approval['approval']:.3f}",
        "HeadHoldoutCILow": f"{head_approval['episode_bootstrap_95_ci'][0]:.3f}",
        "HeadHoldoutCIHigh": f"{head_approval['episode_bootstrap_95_ci'][1]:.3f}",
        "HeadHoldoutDecisive": f"{head_approval['decisive']:,}",
        "HeadHoldoutCandidate": f"{head_approval['candidate_approved']:,}",
        "HeadHoldoutControl": f"{head_approval['control_approved']:,}",
        "HeadHoldoutAbstain": f"{head_approval['abstain']:,}",
        "ReplayApproval": f"{replay_approval['approval']:.3f}",
        "ReplayApprovalCILow": f"{replay_approval['episode_bootstrap_95_ci'][0]:.3f}",
        "ReplayApprovalCIHigh": f"{replay_approval['episode_bootstrap_95_ci'][1]:.3f}",
        "ReplayApprovalDecisive": f"{replay_approval['binary_decisive']:,}",
        "ReplayApprovalDisagreements": f"{replay_approval['disagreements']:,}",
        "ReplayApprovalAbstain": f"{replay_approval['abstain']:,}",
        "ReplayApprovalCandidate": f"{replay_approval['candidate_approved']:,}",
        "ReplayApprovalControl": f"{replay_approval['control_approved']:,}",
        "ReplayApprovalEpisodes": f"{replay_approval['episodes']:,}",
        "ReplayTeamBalancedApproval": f"{heldout['team_balanced_approval']:.3f}",
        "ReplayTeamBalancedTeams": f"{heldout['team_balanced_nonnull_team_count']:,}",
        "AblationOutcomeMismatchUnits": f"{parity['outcome_record_mismatch_units']:,}",
        "AblationSerializedMismatchUnits": f"{parity['serialized_record_mismatch_units']:,}",
        "AblationPlannedPairs": f"{parity['pairs']:,}",
        "AblationStarmieMismatchUnits": f"{parity['by_opponent']['starmie']['any_outcome_record_mismatch_units']:,}",
        "AblationDipplinMismatchUnits": f"{parity['by_opponent']['dipplin']['any_outcome_record_mismatch_units']:,}",
        "AblationWithinCtwoPP": pct(within_ablation["C2-C1 (C2 run)"]["effect"], 3),
        "AblationWithinCthreePP": pct(within_ablation["C3-C1 (C3 run)"]["effect"], 3),
        "AblationWithinCfourPP": pct(within_ablation["C4-C1 (C4 run)"]["effect"], 3),
        "AblationExploratoryCtwoPP": pct(exploratory_ablation["C2-C1"]["effect"], 2),
        "AblationExploratoryCthreePP": pct(exploratory_ablation["C3-C1"]["effect"], 2),
        "AblationExploratoryCfourPP": pct(exploratory_ablation["C4-C1"]["effect"], 2),
        "AblationExploratoryCfourCtwoPP": pct(exploratory_ablation["C4-C2"]["effect"], 2),
        "AblationExploratoryCfourCthreePP": pct(exploratory_ablation["C4-C3"]["effect"], 2),
        "AblationExploratoryInteractionPP": pct(exploratory_interaction["effect"], 2),
        "AblationExploratoryPairs": f"{exploratory_interaction['pairs']:,}",
        "TemporalEffectPP": pct(negatives["temporal_two_turn_takeover"]["effect"], 3),
        "TemporalCILowPP": pct(negatives["temporal_two_turn_takeover"]["ci_low"], 3),
        "TemporalCIHighPP": pct(negatives["temporal_two_turn_takeover"]["ci_high"], 3),
        "TemporalPairs": f"{negatives['temporal_two_turn_takeover']['n']:,}",
        "SequenceEffectPP": pct(negatives["bounded_sequence_oracle"]["effect"], 3),
        "SequenceCILowPP": pct(negatives["bounded_sequence_oracle"]["ci_low"], 3),
        "SequenceCIHighPP": pct(negatives["bounded_sequence_oracle"]["ci_high"], 3),
        "SequenceWorlds": f"{negatives['bounded_sequence_oracle']['n']:,}",
        "SequenceRoots": f"{negatives['bounded_sequence_oracle']['clusters']:,}",
    }
    for name, value in values.items():
        macros.append(f"\\newcommand{{\\{name}}}{{{value}}}")
    replay_ci = replay_approval["episode_bootstrap_95_ci"]
    if replay_ci[0] > 0.5:
        replay_inference = "The interval lay above one half."
    elif replay_ci[1] < 0.5:
        replay_inference = "The interval lay below one half."
    else:
        replay_inference = "The interval included one half."
    head_ci = head_approval["episode_bootstrap_95_ci"]
    if head_ci[0] > 0.5:
        head_inference = "The interval lay above one half."
    elif head_ci[1] < 0.5:
        head_inference = "The interval lay below one half."
    else:
        head_inference = "The interval included one half."
    macros.append(f"\\newcommand{{\\ReplayApprovalInference}}{{{replay_inference}}}")
    macros.append(f"\\newcommand{{\\HeadApprovalInference}}{{{head_inference}}}")
    OUTPUT.mkdir(parents=True, exist_ok=True)
    (OUTPUT / "diagnostic_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")

    tables = OUTPUT / "tables"
    tables.mkdir(parents=True, exist_ok=True)
    display_labels = {
        "B0": "Matched 1", "d842_runtime": "Matched 2",
        "master_v1": "Matched 3", "replay_refresh": "Matched 4",
        "starmie": "Broader 1", "dipplin": "Broader 2",
        "alakazam_no_search": "Broader 3",
    }
    primary_lines = [
        "% Auto-generated by paper/scripts/generate_tables.py; do not edit.",
        r"\begin{table*}",
        r"\caption{Fresh, prospectively specified paired confirmation by fixed opponent and actual order. Effects and percentile intervals are percentage-point differences in win probability (EXP23 minus C0).}",
        r"\label{tab:fresh-cells-release}",
        r"\begin{ruledtabular}",
        r"\begin{tabular}{llrrrr}",
        r"Opponent & Order & Pairs & Effect & 95\% CI & Holm $p$ \\",
        r"\hline",
    ]
    for result in stats["fresh_confirmation"]["cells"]:
        low, high = result["paired_bootstrap_95_ci"]
        primary_lines.append(
            f"{tex_label(display_labels[result['opponent']])} & {tex_label(result['actual_order'])} & "
            f"{result['pairs']} & {100 * result['effect']:+.1f} & "
            f"[{100 * low:+.1f}, {100 * high:+.1f}] & "
            f"{result['holm_adjusted_p_14_cells']:.3f} \\\\"
        )
    primary_lines.extend([r"\end{tabular}", r"\end{ruledtabular}", r"\end{table*}", ""])
    (tables / "primary.tex").write_text("\n".join(primary_lines), encoding="utf-8")

    representation_lines = [
        "% Auto-generated by paper/scripts/generate_tables.py; do not edit.",
        r"\begin{table}",
        r"\caption{Representation and output-module diagnostics on outcome-selected retained feature/action rows. These are not gameplay outcomes.}",
        r"\label{tab:representation}",
        r"\begin{ruledtabular}",
        r"\begin{tabular}{lr}",
        r"Diagnostic & Value \\",
        r"\hline",
        f"Decisions & {corpus['decisions']:,} \\\\ ",
        f"Ordinary PLAY options & {corpus['ordinary_play_options']:,} \\\\ ",
        f"Blind unresolved / repaired bound & {corpus['baseline_unresolved_play_options']:,} / {corpus['identity_bound_play_options']:,} \\\\ ",
        f"Multi-identity PLAY states & {corpus['states_with_two_or_more_play_identities']:,} ({pct(corpus['multi_identity_proportion_of_play_states'])}\\%) \\\\ ",
        f"Index coordinate matches raw / all multi-PLAY unique & {corpus['play_options_with_numeric_index_matching_raw']:,} / {corpus['multi_play_option_states_with_unique_hand_indices']:,} \\\\ ",
        f"Exact within-state blind-input collisions & {corpus['within_state_cross_identity_collision_groups']:,} \\\\ ",
        f"Head disagreement, multi-identity & {pct(disagreement['multi_play_identity']['rate'])}\\% \\\\ ",
        f"Head disagreement, other & {pct(disagreement['other']['rate'])}\\% \\\\ ",
        r"\end{tabular}", r"\end{ruledtabular}", r"\end{table}", "",
    ]
    (tables / "representation.tex").write_text("\n".join(representation_lines), encoding="utf-8")

    ablation_lines = [
        "% Auto-generated by paper/scripts/generate_tables.py; do not edit.",
        r"\begin{table*}",
        r"\caption{Fail-closed four-cell control-parity audit and post-failure descriptive sensitivities. The planned seven-opponent cross-cell analysis was not estimable because repeated C1 records disagreed. Within-run effects are process-sensitive realized comparisons. The five-opponent subset was selected post hoc by whole-package serialized-control parity; it changes the target population and has no inferential interval or test.}",
        r"\label{tab:ablation}",
        r"\begin{ruledtabular}",
        r"\begin{tabular}{llrrl}",
        r"Analysis & Contrast/audit & Pairs & Effect (pp) & Status \\",
        r"\hline",
    ]
    ablation_lines.append(
        f"Planned seven-opponent & C1 parity mismatches & {parity['pairs']:,} & -- & "
        f"invalidated ({parity['outcome_record_mismatch_units']:,} units) \\\\"
    )
    for result in ablation["within_run_descriptive"]["contrasts"]:
        ablation_lines.append(
            f"Within own run & {result['contrast']} & {result['pairs']:,} & "
            f"{100 * result['effect']:+.3f} & descriptive only \\\\"
        )
    for result in ablation["exploratory_reproducible_control_subset"]["contrasts"]:
        ablation_lines.append(
            f"Post hoc five-opponent & {result['contrast']} & {result['pairs']:,} & "
            f"{100 * result['effect']:+.2f} & descriptive only \\\\"
        )
    ablation_lines.append(
        f"Post hoc five-opponent & Interaction & {exploratory_interaction['pairs']:,} & "
        f"{100 * exploratory_interaction['effect']:+.2f} & descriptive only \\\\"
    )
    ablation_lines.extend([r"\end{tabular}", r"\end{ruledtabular}", r"\end{table*}", ""])
    (tables / "ablation.tex").write_text("\n".join(ablation_lines), encoding="utf-8")

    heldout_lines = [
        "% Auto-generated by paper/scripts/generate_tables.py; do not edit.",
        r"\begin{table}",
        r"\caption{Recorded-action agreement conditional on EXP23--C0 semantic disagreement in refresh-held-out, previously inspected 2026-08-13 replay units. Abstentions are excluded from the approval denominator.}",
        r"\label{tab:heldout}",
        r"\begin{ruledtabular}",
        r"\begin{tabular}{lrrrr}",
        r"Stratum & EXP23 & C0 & Abstain & Approval \\",
        r"\hline",
    ]
    heldout_groups = [("Overall", heldout["overall"])] + [
        (name.replace("_", " "), value) for name, value in sorted(heldout["by_identity_state"].items())
    ]
    for label, result in heldout_groups:
        heldout_lines.append(
            f"{tex_label(label)} & {result['candidate_approved']} & {result['control_approved']} & "
            f"{result['abstain']} & {result['approval']:.3f} \\\\"
        )
    heldout_lines.extend([r"\end{tabular}", r"\end{ruledtabular}", r"\end{table}", ""])
    (tables / "heldout.tex").write_text("\n".join(heldout_lines), encoding="utf-8")

    negative_lines = [
        "% Auto-generated by paper/scripts/generate_tables.py; do not edit.",
        r"\begin{table}",
        r"\caption{Independently reaggregated null results with surviving raw artifacts.}",
        r"\label{tab:negative}",
        r"\begin{ruledtabular}",
        r"\begin{tabular}{lrrr}",
        r"Experiment & Units & Effect & 95\% CI \\",
        r"\hline",
    ]
    for result in negative["results"]:
        negative_lines.append(
            f"{tex_label(result['label'])} & {result['n']:,} & {100 * result['effect']:+.3f} & "
            f"[{100 * result['ci_low']:+.3f}, {100 * result['ci_high']:+.3f}] \\\\"
        )
    negative_lines.extend([r"\end{tabular}", r"\end{ruledtabular}", r"\end{table}", ""])
    (tables / "negative.tex").write_text("\n".join(negative_lines), encoding="utf-8")
    print(json.dumps({"macros": len(values), "tables": 5}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
