#!/usr/bin/env python3
"""Create/verify the deterministic, write-once Dipplin S2 qualification.

Only already-produced JSON reports are read. No replay file is ever opened.
The staged report is independently regenerated by its frozen evaluator before
its verdicts are admitted.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Mapping, Sequence


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

SCHEMA = "dipplin-s2-holdout-qualification-v1"
RULE_VERSION = "paired_primary_with_exploratory_safety_veto_v1"
STRENGTH_STAGES = ("stage1", "stage2", "stage3", "stage4")
LABELS = (
    "EQUIVALENT",
    "AGENT_DOMINATES",
    "EXPERT_DOMINATES",
    "INCOMPARABLE",
    "UNCERTIFIABLE",
)
DEFAULT_OUTPUT = ROOT / "data/dipplin_replay_eval/frozen/s2_qualification.json"
DEFAULT_STAGE_REPORT = ROOT / "artifacts/general_strength/s2_stage5/stage5_evaluation.json"
DEFAULT_STAGE_SPEC = ROOT / "data/dipplin_general_strength/s2_stage_evaluation_spec.json"
PINNED_STAGE_EVALUATOR_SHA256 = (
    "A50FDD9ADD0EE15C6FE6EA0409C7B36012C9F3F5A938F92C310B4E2E24CB566B"
)
PINNED_STAGE_EVALUATOR_GIT_BLOB_SHA1 = "08B9B53F0A3A2944303D0975C4F6DA1FB17180AE"
PINNED_STAGE_SPEC_SHA256 = (
    "BF4EC9A7A99067C0DAE8B9F10C00F8CE25FB93C01B5462C06120009CF4F1ED61"
)
PINNED_STAGE_SPEC_GIT_BLOB_SHA1 = "B82A3AC1AD39DB8D03294C3788EFD440B4536FE7"


class QualificationError(RuntimeError):
    """Qualification is pending or an integrity/rule check failed closed."""


@dataclass(frozen=True)
class QualificationContract:
    root: Path
    output: Path
    stage_report: Path
    s1_validation: Path
    s2_validation: Path
    validation_manifest: Path
    evaluator: Path
    stage_evaluator: Path
    stage_spec: Path
    creator: Path
    pins: Mapping[str, str]
    primary_record_count: int
    validation_episode_count: int
    exploratory_hard_ceiling: int
    validation_parameters: Mapping[str, int]


def _canonical_bytes(value: object) -> bytes:
    return json.dumps(
        value, ensure_ascii=True, sort_keys=True, separators=(",", ":"), default=str
    ).encode("utf-8")


def _object_sha256(value: object) -> str:
    return hashlib.sha256(_canonical_bytes(value)).hexdigest().upper()


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest().upper()


def _git_blob_sha1(path: Path) -> str:
    data = path.read_bytes()
    return hashlib.sha1(
        b"blob " + str(len(data)).encode("ascii") + b"\0" + data
    ).hexdigest().upper()


def _mapping(value: object, field: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise QualificationError(f"{field} must be an object")
    return value


def _rows(value: object, field: str) -> list[Mapping[str, Any]]:
    if not isinstance(value, list) or any(not isinstance(row, Mapping) for row in value):
        raise QualificationError(f"{field} must be an array of objects")
    return list(value)


def _integer(value: object, field: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise QualificationError(f"{field} must be an integer")
    return value


def _number(value: object, field: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise QualificationError(f"{field} must be numeric")
    result = float(value)
    if not math.isfinite(result):
        raise QualificationError(f"{field} must be finite")
    return result


def _read_json(path: Path, field: str) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise QualificationError(f"invalid {field}: {exc}") from exc
    if not isinstance(payload, dict):
        raise QualificationError(f"{field} must be a JSON object")
    return payload


def _relative(path: Path, root: Path, field: str) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError as exc:
        raise QualificationError(f"{field} escapes the repository") from exc


def _resolve_report_path(raw: object, *, report: Path, root: Path, field: str) -> Path:
    if not isinstance(raw, str) or not raw:
        raise QualificationError(f"{field} path is missing")
    supplied = Path(raw).expanduser()
    candidates = [supplied] if supplied.is_absolute() else [root / supplied, report.parent / supplied]
    path = next((candidate.resolve() for candidate in candidates if candidate.is_file()), None)
    if path is None:
        raise QualificationError(f"{field} source artifact is missing")
    _relative(path, root, field)
    return path


def _provenance(path: Path, root: Path) -> dict[str, str]:
    return {
        "path": _relative(path, root, "provenance"),
        "sha256": _sha256(path),
        "git_blob_sha1": _git_blob_sha1(path),
    }


def canonical_contract() -> QualificationContract:
    from scripts import evaluate_dipplin_replay_regret as regret

    # Re-verify both frozen packages/results before admitting their pins.
    regret.verify_frozen_s1_provenance()
    regret.verify_s2_candidate()
    return QualificationContract(
        root=ROOT,
        output=regret.DEFAULT_S2_QUALIFICATION,
        stage_report=DEFAULT_STAGE_REPORT,
        s1_validation=regret.DEFAULT_S1_VALIDATION_OUTPUT,
        s2_validation=regret.DEFAULT_S2_VALIDATION_OUTPUT,
        validation_manifest=Path(regret.PINNED_MANIFESTS["VALIDATION"]["path"]),
        evaluator=Path(regret.__file__).resolve(),
        stage_evaluator=ROOT / "scripts/evaluate_dipplin_s2_stages.py",
        stage_spec=DEFAULT_STAGE_SPEC,
        creator=Path(__file__).resolve(),
        pins={
            "s1_archive_sha256": regret.PINNED_S1_ARCHIVE_SHA256,
            "s1_manifest_sha256": regret.PINNED_S1_MANIFEST_SHA256,
            "s1_extracted_tree_sha256": regret.PINNED_S1_EXTRACTED_TREE_SHA256,
            "s1_runtime_tree_sha256": regret.PINNED_S1_RUNTIME_TREE_SHA256,
            "s1_validation_sha256": regret.PINNED_S1_VALIDATION_OUTPUT_SHA256,
            "s2_archive_sha256": regret.PINNED_S2_ARCHIVE_SHA256,
            "s2_manifest_sha256": regret.PINNED_S2_MANIFEST_SHA256,
            "s2_extracted_tree_sha256": regret.PINNED_S2_EXTRACTED_TREE_SHA256,
            "s2_runtime_tree_sha256": regret.PINNED_S2_RUNTIME_TREE_SHA256,
            "manifest_file_sha256": regret.PINNED_MANIFESTS["VALIDATION"]["file_sha256"],
            "manifest_payload_sha256": regret.PINNED_MANIFESTS["VALIDATION"]["payload_sha256"],
            "stage_evaluator_sha256": PINNED_STAGE_EVALUATOR_SHA256,
            "stage_evaluator_git_blob_sha1": PINNED_STAGE_EVALUATOR_GIT_BLOB_SHA1,
            "stage_spec_sha256": PINNED_STAGE_SPEC_SHA256,
            "stage_spec_git_blob_sha1": PINNED_STAGE_SPEC_GIT_BLOB_SHA1,
        },
        primary_record_count=regret.PINNED_S1_PRIMARY_RECORD_COUNT,
        validation_episode_count=regret.EXPECTED_SPLIT_COUNTS["VALIDATION"],
        exploratory_hard_ceiling=regret.S2_EXPLORATORY_HARD_CEILING,
        validation_parameters=dict(regret.FROZEN_SEALED_PARAMETERS),
    )


def _missing(contract: QualificationContract) -> list[str]:
    required = {
        "cumulative Stage1-5 report": contract.stage_report,
        "frozen S1 validation": contract.s1_validation,
        "S2 paired validation": contract.s2_validation,
        "validation manifest": contract.validation_manifest,
        "replay evaluator": contract.evaluator,
        "stage evaluator": contract.stage_evaluator,
        "stage spec": contract.stage_spec,
        "qualification creator": contract.creator,
    }
    return [f"{name} ({path})" for name, path in required.items() if not path.is_file()]


def _verify_manifest(contract: QualificationContract) -> dict[str, str]:
    path = contract.validation_manifest.resolve()
    if _sha256(path) != contract.pins["manifest_file_sha256"]:
        raise QualificationError("validation manifest file hash mismatch")
    payload = _read_json(path, "validation manifest")
    claimed = str(payload.get("manifest_payload_sha256") or "").upper()
    unsigned = dict(payload)
    unsigned.pop("manifest_payload_sha256", None)
    calculated = hashlib.sha256(
        json.dumps(unsigned, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest().upper()
    if claimed != contract.pins["manifest_payload_sha256"] or claimed != calculated:
        raise QualificationError("validation manifest payload digest mismatch")
    if (
        payload.get("dataset") != "dipplin_fresh_expert_replay_eval_v1"
        or payload.get("split") != "VALIDATION"
        or payload.get("sealed") is not False
        or _integer(payload.get("episode_count"), "validation manifest episode_count")
        != contract.validation_episode_count
    ):
        raise QualificationError("validation manifest split contract mismatch")
    return {
        "path": _relative(path, contract.root, "validation manifest"),
        "file_sha256": _sha256(path),
        "payload_sha256": claimed,
    }


def _sum_cells(cells: Sequence[Mapping[str, Any]], field: str) -> dict[str, int]:
    if not cells:
        raise QualificationError(f"{field} cannot be empty")
    keys = (
        "games", "scheduled_games", "wins", "losses", "draws", "failed_games",
        "hero_policy_errors", "opponent_policy_errors", "hero_illegal_actions",
        "opponent_illegal_actions",
    )
    totals = {key: 0 for key in keys}
    for index, cell in enumerate(cells):
        for key in keys:
            value = _integer(cell.get(key), f"{field}[{index}].{key}")
            if value < 0:
                raise QualificationError(f"{field}[{index}].{key} cannot be negative")
            totals[key] += value
    if totals["wins"] + totals["losses"] + totals["draws"] != totals["games"]:
        raise QualificationError(f"{field} game accounting mismatch")
    if totals["scheduled_games"] != totals["games"]:
        raise QualificationError(f"{field} scheduled/completed games mismatch")
    if any(totals[key] for key in keys[5:]):
        raise QualificationError(f"{field} contains an operational failure")
    return totals


def _verify_pooled(value: object, totals: Mapping[str, int], field: str) -> None:
    pooled = _mapping(value, field)
    for key, expected in totals.items():
        if _integer(pooled.get(key), f"{field}.{key}") != expected:
            raise QualificationError(f"{field}.{key} does not reaggregate")
    expected_rate = totals["wins"] / totals["games"]
    if not math.isclose(
        _number(pooled.get("win_rate"), f"{field}.win_rate"), expected_rate,
        rel_tol=0.0, abs_tol=1e-12,
    ):
        raise QualificationError(f"{field}.win_rate does not reaggregate")


def _wilson(wins: int, games: int, z: float = 1.959963984540054) -> tuple[float, float]:
    proportion = wins / games
    denominator = 1.0 + z * z / games
    center = (proportion + z * z / (2.0 * games)) / denominator
    margin = z * math.sqrt(
        (proportion * (1.0 - proportion) + z * z / (4.0 * games)) / games
    ) / denominator
    return max(0.0, center - margin), min(1.0, center + margin)


def _newcombe_upper(candidate_wins: int, candidate_games: int, control_wins: int, control_games: int) -> float:
    p1, p0 = candidate_wins / candidate_games, control_wins / control_games
    _, u1 = _wilson(candidate_wins, candidate_games)
    l0, _ = _wilson(control_wins, control_games)
    return min(1.0, p1 - p0 + math.sqrt((u1 - p1) ** 2 + (p0 - l0) ** 2))


def _verify_stage4(stage: Mapping[str, Any]) -> dict[str, Any]:
    baseline = _rows(stage.get("baseline_cells"), "stage4 controls")
    candidate = _rows(stage.get("candidate_cells"), "stage4 candidates")

    def by_order(cells: Sequence[Mapping[str, Any]], field: str) -> dict[str, dict[str, int]]:
        result: dict[str, dict[str, int]] = {}
        for order in ("first", "second"):
            selected = [row for row in cells if row.get("actual_order") == order]
            result[order] = _sum_cells(selected, f"{field}.{order}")
        if len(cells) != sum(len([row for row in cells if row.get("actual_order") == order]) for order in ("first", "second")):
            raise QualificationError(f"{field} contains an unexpected order")
        return result

    controls = by_order(baseline, "stage4 controls")
    candidates = by_order(candidate, "stage4 candidates")
    if {
        order: (controls[order]["wins"], controls[order]["games"])
        for order in ("first", "second")
    } != {"first": (302, 500), "second": (197, 500)}:
        raise QualificationError("stage4 immutable S1-vs-S1 controls mismatch")
    if any(candidates[order]["games"] != 300 for order in ("first", "second")):
        raise QualificationError("stage4 candidate games/order mismatch")
    per_order_delta = {
        order: candidates[order]["wins"] / candidates[order]["games"]
        - controls[order]["wins"] / controls[order]["games"]
        for order in ("first", "second")
    }
    candidate_wins = sum(candidates[order]["wins"] for order in ("first", "second"))
    candidate_games = 600
    control_wins = 499
    control_games = 1000
    raw_rate = candidate_wins / candidate_games
    balanced_delta = raw_rate - control_wins / control_games
    upper = {
        order: _newcombe_upper(
            candidates[order]["wins"], candidates[order]["games"],
            controls[order]["wins"], controls[order]["games"],
        )
        for order in ("first", "second")
    }
    upper["balanced_pooled"] = _newcombe_upper(
        candidate_wins, candidate_games, control_wins, control_games
    )
    if (
        min(per_order_delta.values()) < -0.04
        or balanced_delta < -0.03
        or raw_rate < 0.47
        or min(upper.values()) < 0.0
    ):
        raise QualificationError("stage4 independently recomputed gate failed")
    return {
        "controls": {order: controls[order] for order in ("first", "second")},
        "candidates": {order: candidates[order] for order in ("first", "second")},
        "candidate_minus_control_by_order": per_order_delta,
        "candidate_raw_pooled_win_rate": raw_rate,
        "balanced_pooled_candidate_minus_control": balanced_delta,
        "newcombe_upper_by_order_and_pool": upper,
    }


QUALITY_COUNT_KEYS = (
    "proposal_error_rows",
    "candidate_policy_error_rows",
    "candidate_action_unstable_rows",
    "uncertifiable_rows",
    "incomparable_rows",
)
ARCHETYPE_COUNT_KEYS = (
    "opponent_archetype_decision_counts",
    "opponent_archetype_episode_counts",
    "opponent_archetypes",
)


def _classification_summary(
    value: object, field: str, *, require_quality_counts: bool = False
) -> dict[str, Any]:
    summary = _mapping(value, field)
    counts = _mapping(summary.get("classification_counts"), f"{field}.classification_counts")
    rates = _mapping(summary.get("episode_rates"), f"{field}.episode_rates")
    result = {
        "episode_count": _integer(summary.get("episode_count"), f"{field}.episode_count"),
        "decision_count": _integer(summary.get("decision_count"), f"{field}.decision_count"),
        "classification_counts": {
            label: _integer(counts.get(label), f"{field}.classification_counts.{label}")
            for label in LABELS
        },
        "episode_rates": {
            label: _number(rates.get(label), f"{field}.episode_rates.{label}")
            for label in LABELS
        },
    }
    if require_quality_counts:
        quality = _mapping(summary.get("quality_counts"), f"{field}.quality_counts")
        if set(quality) != set(QUALITY_COUNT_KEYS):
            raise QualificationError(f"{field}.quality_counts keys mismatch")
        result["quality_counts"] = {
            key: _integer(quality.get(key), f"{field}.quality_counts.{key}")
            for key in QUALITY_COUNT_KEYS
        }
        for key in ARCHETYPE_COUNT_KEYS:
            claimed = _mapping(summary.get(key), f"{field}.{key}")
            result[key] = {
                str(name): _integer(value, f"{field}.{key}.{name}")
                for name, value in sorted(claimed.items())
            }
        if summary.get("opponent_archetypes_basis") != "unique_episode_id":
            raise QualificationError(f"{field}.opponent_archetypes_basis mismatch")
        result["opponent_archetypes_basis"] = "unique_episode_id"
    return result


def _structured_families(value: object, field: str) -> list[dict[str, str]]:
    rows = _rows(value, field)
    result: list[dict[str, str]] = []
    for index, row in enumerate(rows):
        item: dict[str, str] = {}
        for key in ("classification", "decision_family", "reason"):
            raw = row.get(key)
            if not isinstance(raw, str):
                raise QualificationError(f"{field}[{index}].{key} must be a string")
            item[key] = raw
        result.append(item)
    return result


def _stage5_report_view(
    stage: Mapping[str, Any], contract: QualificationContract
) -> dict[str, Any]:
    def source_summary(
        value: object, field: str, *, require_quality_counts: bool
    ) -> dict[str, Any]:
        summary = _mapping(value, field)
        source = _mapping(summary.get("source"), f"{field}.source")
        source_path = _resolve_report_path(
            source.get("path"),
            report=contract.stage_report,
            root=contract.root,
            field=f"{field}.source",
        )
        digest = str(source.get("artifact_sha256") or "").upper()
        if len(digest) != 64 or _sha256(source_path) != digest:
            raise QualificationError(f"{field} source artifact hash mismatch")
        return {
            "source": {
                "path": _relative(source_path, contract.root, f"{field}.source"),
                "sha256": digest,
            },
            **_classification_summary(
                summary, field, require_quality_counts=require_quality_counts
            ),
        }

    paired_ids = _mapping(stage.get("paired_record_ids"), "stage5.paired_record_ids")
    transitions = _mapping(stage.get("paired_transitions"), "stage5.paired_transitions")
    matrix_value = _mapping(transitions.get("matrix"), "stage5.paired_transitions.matrix")
    matrix: dict[str, dict[str, int]] = {}
    for before in LABELS:
        row = _mapping(matrix_value.get(before), f"stage5.matrix.{before}")
        matrix[before] = {
            after: _integer(row.get(after), f"stage5.matrix.{before}.{after}")
            for after in LABELS
        }
    families = _mapping(stage.get("failure_families"), "stage5.failure_families")
    decision = _mapping(stage.get("decision"), "stage5.decision")
    gates = _mapping(decision.get("gates"), "stage5.decision.gates")
    if any(not isinstance(value, bool) for value in gates.values()):
        raise QualificationError("stage5 decision gates must be booleans")
    return {
        "baseline": source_summary(
            stage.get("baseline"),
            "stage5.baseline",
            require_quality_counts=False,
        ),
        "candidate": source_summary(
            stage.get("candidate"),
            "stage5.candidate",
            require_quality_counts=True,
        ),
        "paired_record_ids": {
            "count": _integer(paired_ids.get("count"), "stage5.paired_record_ids.count"),
            "sequence_sha256": str(paired_ids.get("sequence_sha256") or "").upper(),
            "exact_order_match": paired_ids.get("exact_order_match"),
        },
        "paired_transitions": {
            "ed_to_non_ed": _integer(
                transitions.get("ed_to_non_ed"), "stage5.transitions.ed_to_non_ed"
            ),
            "non_ed_to_ed": _integer(
                transitions.get("non_ed_to_ed"), "stage5.transitions.non_ed_to_ed"
            ),
            "matrix": matrix,
            "ed_count_identity_verified": transitions.get(
                "ed_count_identity_verified"
            ),
            "ed_to_non_ed_definition": transitions.get("ed_to_non_ed_definition"),
        },
        "exploratory_safety_veto": {
            **_classification_summary(
                stage.get("exploratory_safety_veto"),
                "stage5.exploratory_safety_veto",
                require_quality_counts=True,
            ),
            "efficacy_credit_permitted": _mapping(
                stage.get("exploratory_safety_veto"),
                "stage5.exploratory_safety_veto",
            ).get("efficacy_credit_permitted"),
        },
        "failure_families": {
            key: _structured_families(
                families.get(key), f"stage5.failure_families.{key}"
            )
            for key in ("baseline", "candidate", "new")
        },
        "decision": {
            "verdict": decision.get("verdict"),
            "passed": decision.get("passed"),
            "gates": dict(gates),
        },
    }


def _verify_stages(
    contract: QualificationContract,
    *,
    recompute: Callable[[Path], Mapping[str, Any]] | None = None,
) -> dict[str, Any]:
    path = contract.stage_report.resolve()
    report = _read_json(path, "cumulative Stage1-5 report")
    if report.get("schema") != "dipplin-s2-stage-evaluation-v1":
        raise QualificationError("staged report schema mismatch")
    spec_info = _mapping(report.get("spec"), "staged report spec")
    spec_path = _resolve_report_path(
        spec_info.get("path"), report=path, root=contract.root, field="stage spec"
    )
    stage_evaluator_provenance = _provenance(
        contract.stage_evaluator, contract.root
    )
    spec_provenance = _provenance(spec_path, contract.root)
    if (
        spec_path != contract.stage_spec.resolve()
        or spec_provenance["sha256"] != contract.pins["stage_spec_sha256"]
        or spec_provenance["git_blob_sha1"]
        != contract.pins["stage_spec_git_blob_sha1"]
        or stage_evaluator_provenance["sha256"]
        != contract.pins["stage_evaluator_sha256"]
        or stage_evaluator_provenance["git_blob_sha1"]
        != contract.pins["stage_evaluator_git_blob_sha1"]
        or spec_provenance["sha256"]
        != str(spec_info.get("sha256") or "").upper()
    ):
        raise QualificationError("stage spec hash mismatch")
    if recompute is None:
        from scripts.evaluate_dipplin_s2_stages import evaluate_spec

        recompute = evaluate_spec
    regenerated = dict(recompute(spec_path))
    if regenerated != report:
        raise QualificationError("staged report differs from independent exact recomputation")
    for arm in ("baseline", "candidate"):
        identity = _mapping(report.get(arm), f"stage report {arm}")
        prefix = "s1" if arm == "baseline" else "s2"
        package = _mapping(identity.get("package_manifest"), f"stage report {arm} package")
        if (
            str(identity.get("archive_sha256") or "").upper() != contract.pins[f"{prefix}_archive_sha256"]
            or str(identity.get("tree_sha256") or "").upper() != contract.pins[f"{prefix}_extracted_tree_sha256"]
            or str(package.get("sha256") or "").upper() != contract.pins[f"{prefix}_manifest_sha256"]
        ):
            raise QualificationError(f"stage report {arm} package pins mismatch")
    stage_map = _mapping(report.get("stages"), "staged report stages")
    artifacts: list[dict[str, str]] = []
    verdicts: dict[str, str] = {}
    summaries: dict[str, Any] = {}
    for name in STRENGTH_STAGES:
        stage = _mapping(stage_map.get(name), f"stages.{name}")
        if stage.get("status") != "EVALUATED":
            raise QualificationError(f"{name} is pending or not evaluated")
        decision = _mapping(stage.get("decision"), f"{name}.decision")
        verdict = str(decision.get("verdict") or "")
        allowed = {"PROMISING", "STRONG"} if name == "stage1" else {"PASS", "STRONG"}
        if verdict not in allowed:
            raise QualificationError(f"{name} did not pass")
        gates = _mapping(decision.get("gates"), f"{name}.decision.gates")
        if (
            not gates
            or any(not isinstance(value, bool) for value in gates.values())
            or any(value is not True for value in gates.values())
        ):
            raise QualificationError(f"{name} has a failed decision gate")
        if name != "stage1" and decision.get("passed") is not True:
            raise QualificationError(f"{name} is not marked passed")
        verdicts[name] = verdict
        for arm in ("baseline", "candidate"):
            cells = _rows(stage.get(f"{arm}_cells"), f"{name}.{arm}_cells")
            totals = _sum_cells(cells, f"{name}.{arm}_cells")
            _verify_pooled(
                _mapping(stage.get("pooled"), f"{name}.pooled").get(arm),
                totals,
                f"{name}.pooled.{arm}",
            )
            for cell in cells:
                source = _mapping(cell.get("source"), f"{name}.{arm}.source")
                source_path = _resolve_report_path(
                    source.get("path"), report=path, root=contract.root,
                    field=f"{name}.{arm}.source",
                )
                expected = str(source.get("artifact_sha256") or "").upper()
                if len(expected) != 64 or _sha256(source_path) != expected:
                    raise QualificationError(f"{name}.{arm} source artifact hash mismatch")
                artifacts.append({
                    "stage": name,
                    "arm": arm,
                    "id": str(cell.get("id") or ""),
                    "path": _relative(source_path, contract.root, "stage source"),
                    "sha256": expected,
                })
        if name == "stage4":
            summaries[name] = _verify_stage4(stage)
    stage5 = _mapping(stage_map.get("stage5"), "stages.stage5")
    if stage5.get("status") != "EVALUATED":
        raise QualificationError("stage5 is pending or not evaluated")
    stage5_decision = _mapping(stage5.get("decision"), "stage5.decision")
    stage5_gates = _mapping(stage5_decision.get("gates"), "stage5.decision.gates")
    if (
        stage5_decision.get("verdict") != "PASS"
        or stage5_decision.get("passed") is not True
        or not stage5_gates
        or any(not isinstance(value, bool) or value is not True for value in stage5_gates.values())
    ):
        raise QualificationError("stage5 did not pass")
    verdicts["stage5"] = "PASS"
    stage5_view = _stage5_report_view(stage5, contract)
    for arm in ("baseline", "candidate"):
        source = stage5_view[arm]["source"]
        artifacts.append({
            "stage": "stage5",
            "arm": arm,
            "id": "frozen_s1_validation" if arm == "baseline" else "s2_validation",
            "path": source["path"],
            "sha256": source["sha256"],
        })
    return {
        "report": {
            "path": _relative(path, contract.root, "stage report"),
            "sha256": _sha256(path),
            "schema": report["schema"],
        },
        "spec": spec_provenance,
        "stage_evaluator": stage_evaluator_provenance,
        "verdicts": verdicts,
        "source_artifacts": artifacts,
        "independent_reaggregation": summaries,
        "stage5_contract_view": stage5_view,
    }


def _counts(rows: Sequence[Mapping[str, Any]], field: str) -> Counter[str]:
    counts: Counter[str] = Counter()
    for index, row in enumerate(rows):
        label = str(row.get("classification") or "")
        if label not in LABELS:
            raise QualificationError(f"{field}[{index}] classification is invalid")
        counts[label] += 1
    return counts


def _episode_groups(
    rows: Sequence[Mapping[str, Any]], field: str
) -> dict[str, list[Mapping[str, Any]]]:
    grouped: dict[str, list[Mapping[str, Any]]] = defaultdict(list)
    for index, row in enumerate(rows):
        episode_id = row.get("episode_id")
        if (
            isinstance(episode_id, bool)
            or not isinstance(episode_id, (int, str))
            or not str(episode_id)
        ):
            raise QualificationError(f"{field}[{index}].episode_id is invalid")
        grouped[str(episode_id)].append(row)
    return dict(grouped)


def _episode_rates(
    rows: Sequence[Mapping[str, Any]], field: str
) -> dict[str, float]:
    grouped = _episode_groups(rows, field)
    return {
        label: (
            sum(
                sum(row.get("classification") == label for row in values)
                / len(values)
                for values in grouped.values()
            )
            / len(grouped)
            if grouped
            else 0.0
        )
        for label in LABELS
    }


def _verify_aggregate(
    value: object,
    rows: Sequence[Mapping[str, Any]],
    field: str,
    *,
    require_quality_counts: bool = False,
) -> dict[str, Any]:
    aggregate = _mapping(value, field)
    counts = _counts(rows, field)
    episode_rates = _episode_rates(rows, field)
    episode_count = len(_episode_groups(rows, field))
    claimed = _mapping(aggregate.get("classification_counts"), f"{field}.counts")
    if (
        _integer(aggregate.get("decision_count"), f"{field}.decision_count") != len(rows)
        or _integer(aggregate.get("episode_count"), f"{field}.episode_count")
        != episode_count
        or any(_integer(claimed.get(label), f"{field}.{label}") != counts[label] for label in LABELS)
    ):
        raise QualificationError(f"{field} counts do not reaggregate")
    rates = _mapping(aggregate.get("decision_rates"), f"{field}.decision_rates")
    claimed_episode_rates = _mapping(
        aggregate.get("episode_rates"), f"{field}.episode_rates"
    )
    for label in LABELS:
        expected = counts[label] / len(rows) if rows else 0.0
        if not math.isclose(_number(rates.get(label), f"{field}.{label} rate"), expected, rel_tol=0.0, abs_tol=1e-15):
            raise QualificationError(f"{field} rates do not reaggregate")
        if not math.isclose(
            _number(
                claimed_episode_rates.get(label),
                f"{field}.{label} episode rate",
            ),
            episode_rates[label],
            rel_tol=0.0,
            abs_tol=1e-15,
        ):
            raise QualificationError(f"{field} episode rates do not reaggregate")
    for alias, label in (
        ("expert_dominates_rate", "EXPERT_DOMINATES"),
        ("agent_dominates_rate", "AGENT_DOMINATES"),
    ):
        if not math.isclose(
            _number(aggregate.get(alias), f"{field}.{alias}"),
            episode_rates[label],
            rel_tol=0.0,
            abs_tol=1e-15,
        ):
            raise QualificationError(f"{field} episode rate does not reaggregate")
    quality_counts: dict[str, int] | None = None
    archetype_decision_counts: dict[str, int] | None = None
    archetype_episode_counts: dict[str, int] | None = None
    if require_quality_counts:
        proposal_errors = sum(row.get("proposal_error") is not None for row in rows)
        action_unstable = sum(
            row.get("proposal_error") is not None
            and (
                "unstable" in str(row.get("proposal_error")).lower()
                or str(row.get("uncertifiable_reason") or "").lower()
                in {"candidate_action_unstable", "action_unstable"}
            )
            for row in rows
        )
        quality_counts = {
            "proposal_error_rows": proposal_errors,
            "candidate_policy_error_rows": proposal_errors - action_unstable,
            "candidate_action_unstable_rows": action_unstable,
            "uncertifiable_rows": counts["UNCERTIFIABLE"],
            "incomparable_rows": counts["INCOMPARABLE"],
        }
        claimed_quality = _mapping(
            aggregate.get("quality_counts"), f"{field}.quality_counts"
        )
        if set(claimed_quality) != set(quality_counts) or any(
            _integer(
                claimed_quality.get(key), f"{field}.quality_counts.{key}"
            )
            != expected
            for key, expected in quality_counts.items()
        ):
            raise QualificationError(f"{field} quality counts do not reaggregate")
        decision_archetypes: Counter[str] = Counter()
        episode_archetypes: dict[str, str] = {}
        for index, row in enumerate(rows):
            episode_id = str(row.get("episode_id"))
            archetype = str(row.get("opponent_archetype") or "unknown")
            if (
                episode_id in episode_archetypes
                and episode_archetypes[episode_id] != archetype
            ):
                raise QualificationError(
                    f"{field}[{index}] has inconsistent opponent archetype"
                )
            episode_archetypes[episode_id] = archetype
            decision_archetypes[archetype] += 1
        archetype_decision_counts = dict(sorted(decision_archetypes.items()))
        archetype_episode_counts = dict(
            sorted(Counter(episode_archetypes.values()).items())
        )
        for key, expected in (
            ("opponent_archetype_decision_counts", archetype_decision_counts),
            ("opponent_archetype_episode_counts", archetype_episode_counts),
            ("opponent_archetypes", archetype_episode_counts),
        ):
            claimed = _mapping(aggregate.get(key), f"{field}.{key}")
            if set(claimed) != set(expected) or any(
                _integer(claimed.get(name), f"{field}.{key}.{name}") != count
                for name, count in expected.items()
            ):
                raise QualificationError(f"{field} {key} does not reaggregate")
        if aggregate.get("opponent_archetypes_basis") != "unique_episode_id":
            raise QualificationError(f"{field} opponent archetype basis mismatch")
    intervals = _mapping(
        aggregate.get("episode_bootstrap_95"), f"{field}.episode_bootstrap_95"
    )
    for label in LABELS:
        interval = intervals.get(label)
        if not isinstance(interval, list) or len(interval) != 2:
            raise QualificationError(f"{field}.{label} bootstrap interval is invalid")
        lower = _number(interval[0], f"{field}.{label} bootstrap lower")
        upper = _number(interval[1], f"{field}.{label} bootstrap upper")
        if lower < 0.0 or lower > upper or upper > 1.0:
            raise QualificationError(f"{field}.{label} bootstrap interval is invalid")
    result = {
        "episode_count": episode_count,
        "decision_count": len(rows),
        "classification_counts": {label: counts[label] for label in LABELS},
        "episode_rates": episode_rates,
    }
    if quality_counts is not None:
        result["quality_counts"] = quality_counts
        result["opponent_archetype_decision_counts"] = archetype_decision_counts
        result["opponent_archetype_episode_counts"] = archetype_episode_counts
        result["opponent_archetypes"] = archetype_episode_counts
        result["opponent_archetypes_basis"] = "unique_episode_id"
    return result


def _failure_family(row: Mapping[str, Any]) -> tuple[str, str, str] | None:
    label = str(row.get("classification") or "")
    if label not in {"EXPERT_DOMINATES", "INCOMPARABLE", "UNCERTIFIABLE"}:
        return None
    reason = ""
    if label == "UNCERTIFIABLE":
        raw = str(
            row.get("uncertifiable_reason")
            or row.get("proposal_error")
            or "unknown"
        )
        lowered = raw.lower()
        if "action_unstable" in lowered:
            reason = "action_unstable"
        elif "policy_error" in lowered or row.get("proposal_error"):
            reason = "policy_error"
        else:
            reason = raw
    return (label, str(row.get("decision_family") or "unknown"), reason)


def _families_payload(
    families: Sequence[tuple[str, str, str]],
) -> list[dict[str, str]]:
    return [
        {
            "classification": item[0],
            "decision_family": item[1],
            "reason": item[2],
        }
        for item in families
    ]


def _verify_validations(contract: QualificationContract) -> dict[str, Any]:
    if _sha256(contract.s1_validation) != contract.pins["s1_validation_sha256"]:
        raise QualificationError("frozen S1 validation hash mismatch")
    s1 = _read_json(contract.s1_validation, "S1 validation")
    s2 = _read_json(contract.s2_validation, "S2 validation")
    s1_rows = _rows(s1.get("decision_rows"), "S1 rows")
    sets = _mapping(s2.get("evaluation_sets"), "S2 evaluation sets")
    primary = _mapping(sets.get("paired_primary"), "S2 paired primary")
    exploratory = _mapping(sets.get("s2_exploratory"), "S2 exploratory")
    primary_rows = _rows(primary.get("decision_rows"), "S2 primary rows")
    exploratory_rows = _rows(exploratory.get("decision_rows"), "S2 exploratory rows")
    def record_ids(rows: Sequence[Mapping[str, Any]], field: str) -> list[str]:
        result: list[str] = []
        for index, row in enumerate(rows):
            value = row.get("record_id")
            if not isinstance(value, str) or not value:
                raise QualificationError(f"{field}[{index}].record_id is invalid")
            result.append(value)
        return result

    s1_ids = record_ids(s1_rows, "S1 rows")
    primary_ids = record_ids(primary_rows, "S2 primary rows")
    exploratory_ids = record_ids(exploratory_rows, "S2 exploratory rows")
    candidate = _mapping(s2.get("evaluated_candidate"), "S2 candidate provenance")
    baseline = _mapping(s2.get("baseline_incumbent_s1"), "S2 baseline provenance")
    run = _mapping(s2.get("run_contract"), "S2 run contract")
    selection = _mapping(primary.get("selection"), "S2 primary selection")
    exploratory_selection = _mapping(
        exploratory.get("selection"), "S2 exploratory selection"
    )
    universe = _mapping(s2.get("universe_counts"), "S2 universe")
    if (
        s1.get("schema") != "dipplin-replay-regret-v1"
        or s2.get("schema") != "dipplin-replay-regret-v2"
        or s1.get("split") != "VALIDATION"
        or s1.get("sealed") is not False
        or s2.get("split") != "VALIDATION"
        or s2.get("sealed") is not False
        or s2.get("candidate_variant") != "s2"
        or s2.get("headline_set") != "paired_primary"
        or s2.get("aggregate_alias") != "evaluation_sets.paired_primary.aggregate"
        or s2.get("aggregate") != primary.get("aggregate")
        or "decision_rows" in s2
        or "combined_rate" in s2
        or s2.get("combined_rate_permitted") is not False
        or len(s1_rows) != contract.primary_record_count
        or primary_ids != s1_ids
        or len(set(s1_ids)) != len(s1_ids)
        or str(selection.get("record_id_sequence_sha256") or "").upper()
        != _object_sha256(s1_ids)
        or selection.get("mode") != "exact_frozen_s1_record_ids"
        or selection.get("source_result_sha256")
        != contract.pins["s1_validation_sha256"]
        or _integer(selection.get("record_count"), "S2 primary record count")
        != contract.primary_record_count
        or selection.get("order_preserved") is not True
        or primary.get("role") != "qualification_primary"
        or str(baseline.get("validation_result_sha256") or "").upper()
        != contract.pins["s1_validation_sha256"]
        or any(
            str(baseline.get(key) or "").upper() != contract.pins[f"s1_{pin}"]
            for key, pin in (
                ("archive_sha256", "archive_sha256"),
                ("manifest_sha256", "manifest_sha256"),
                ("extracted_tree_sha256", "extracted_tree_sha256"),
                ("runtime_source_tree_sha256", "runtime_tree_sha256"),
            )
        )
        or any(
            str(candidate.get(key) or "").upper() != contract.pins[f"s2_{pin}"]
            for key, pin in (
                ("archive_sha256", "archive_sha256"),
                ("manifest_sha256", "manifest_sha256"),
                ("extracted_tree_sha256", "extracted_tree_sha256"),
                ("runtime_source_tree_sha256", "runtime_tree_sha256"),
            )
        )
        or str(s2.get("manifest_payload_sha256") or "").upper()
        != contract.pins["manifest_payload_sha256"]
        or run.get("candidate") != "s2"
        or run.get("evaluator") != _provenance(contract.evaluator, contract.root)
        or run.get("parameters") != dict(contract.validation_parameters)
        or _integer(
            run.get("full_manifest_episode_count"),
            "S2 run full_manifest_episode_count",
        )
        != contract.validation_episode_count
        or str(run.get("validation_manifest_file_sha256") or "").upper()
        != contract.pins["manifest_file_sha256"]
        or str(run.get("validation_manifest_payload_sha256") or "").upper()
        != contract.pins["manifest_payload_sha256"]
        or str(run.get("baseline_s1_validation_result_sha256") or "").upper()
        != contract.pins["s1_validation_sha256"]
    ):
        raise QualificationError("paired validation provenance/ordered-ID contract mismatch")
    if (
        exploratory.get("role") != "exploratory_safety_veto_only"
        or exploratory.get("safety_veto_only") is not True
        or exploratory.get("eligible_for_efficacy_rate") is not False
        or len(exploratory_rows) > contract.exploratory_hard_ceiling
        or len(set(exploratory_ids)) != len(exploratory_ids)
        or set(primary_ids).intersection(exploratory_ids)
        or exploratory_selection.get("mode")
        != "exhaustive_disjoint_out_of_primary_s2_override_disagreements"
        or exploratory_selection.get("requires_trustworthy_s2_override_delta") is not True
        or exploratory_selection.get("requires_candidate_expert_disagreement") is not True
        or _integer(exploratory_selection.get("hard_ceiling"), "exploratory hard ceiling")
        != contract.exploratory_hard_ceiling
        or exploratory_selection.get("disjoint_from") != "paired_primary"
    ):
        raise QualificationError("exploratory validation selection contract mismatch")
    universe_values = {
        key: _integer(universe.get(key), f"S2 universe.{key}")
        for key in (
            "manifest_episode_count",
            "useful_prompt_count",
            "paired_primary_record_count",
            "out_of_primary_useful_prompt_count",
            "s2_override_prompt_count",
            "paired_primary_s2_override_prompt_count",
            "out_of_primary_s2_override_prompt_count",
            "out_of_primary_s2_override_expert_equivalent_count",
            "out_of_primary_s2_override_disagreement_count",
            "s2_exploratory_record_count",
            "s2_exploratory_hard_ceiling",
        )
    }
    if (
        any(value < 0 for value in universe_values.values())
        or universe_values["manifest_episode_count"]
        != contract.validation_episode_count
        or universe_values["paired_primary_record_count"] != contract.primary_record_count
        or universe_values["useful_prompt_count"]
        != universe_values["paired_primary_record_count"]
        + universe_values["out_of_primary_useful_prompt_count"]
        or universe_values["s2_override_prompt_count"]
        != universe_values["paired_primary_s2_override_prompt_count"]
        + universe_values["out_of_primary_s2_override_prompt_count"]
        or universe_values["out_of_primary_s2_override_prompt_count"]
        != universe_values["out_of_primary_s2_override_expert_equivalent_count"]
        + universe_values["out_of_primary_s2_override_disagreement_count"]
        or universe_values["out_of_primary_s2_override_disagreement_count"]
        != len(exploratory_rows)
        or universe_values["s2_exploratory_record_count"] != len(exploratory_rows)
        or universe_values["s2_exploratory_hard_ceiling"]
        != contract.exploratory_hard_ceiling
        or universe_values["paired_primary_s2_override_prompt_count"]
        > contract.primary_record_count
        or universe_values["out_of_primary_s2_override_prompt_count"]
        > universe_values["out_of_primary_useful_prompt_count"]
    ):
        raise QualificationError("exploratory universe arithmetic mismatch")
    primary_override_count = 0
    candidate_policy_errors = 0
    for index, row in enumerate([*primary_rows, *exploratory_rows]):
        if (
            row.get("candidate_variant") != "s2"
            or row.get("candidate_s2_enabled") is not True
        ):
            raise QualificationError(f"S2 candidate row {index} lacks S2 mode proof")
        trustworthy = row.get("s2_override_telemetry_trustworthy")
        if not isinstance(trustworthy, bool) or (
            trustworthy is False and not row.get("proposal_error")
        ):
            raise QualificationError(f"S2 candidate row {index} telemetry trust is invalid")
        delta = _integer(
            row.get("s2_pre_attack_sequence_proof_overrides_delta"),
            f"S2 candidate row {index} override delta",
        )
        if delta not in (0, 1):
            raise QualificationError(f"S2 candidate row {index} override delta is invalid")
        if index < len(primary_rows):
            primary_override_count += delta
        candidate_policy_errors += bool(row.get("proposal_error"))
    if (
        primary_override_count
        != universe_values["paired_primary_s2_override_prompt_count"]
    ):
        raise QualificationError("paired-primary override count does not reaggregate")
    for row in exploratory_rows:
        if (
            row.get("s2_override_telemetry_trustworthy") is not True
            or _integer(row.get("s2_pre_attack_sequence_proof_overrides_delta"), "S2 override delta") != 1
            or row.get("semantic_equivalent") is not False
            or bool(row.get("proposal_error"))
        ):
            raise QualificationError("exploratory row is not a trustworthy S2 disagreement")
    s1_summary = _verify_aggregate(s1.get("aggregate"), s1_rows, "S1 aggregate")
    s2_summary = _verify_aggregate(
        primary.get("aggregate"),
        primary_rows,
        "S2 primary aggregate",
        require_quality_counts=True,
    )
    exploratory_summary = _verify_aggregate(
        exploratory.get("aggregate"),
        exploratory_rows,
        "S2 exploratory aggregate",
        require_quality_counts=True,
    )
    if (
        s1_summary["episode_count"] != contract.validation_episode_count
        or s2_summary["episode_count"] != contract.validation_episode_count
    ):
        raise QualificationError("paired validation episode coverage mismatch")
    manifest_payload = _read_json(contract.validation_manifest, "validation manifest")
    manifest_episodes = _rows(
        manifest_payload.get("episodes"), "validation manifest episodes"
    )
    manifest_ids: set[str] = set()
    manifest_archetypes: Counter[str] = Counter()
    for index, episode in enumerate(manifest_episodes):
        episode_id = episode.get("episode_id")
        if (
            isinstance(episode_id, bool)
            or not isinstance(episode_id, (int, str))
            or not str(episode_id)
            or str(episode_id) in manifest_ids
        ):
            raise QualificationError(
                f"validation manifest episode {index} identity is invalid"
            )
        opponent = _mapping(
            episode.get("opponent"), f"validation manifest episode {index} opponent"
        )
        archetype = opponent.get("archetype")
        if not isinstance(archetype, str) or not archetype:
            raise QualificationError(
                f"validation manifest episode {index} archetype is invalid"
            )
        manifest_ids.add(str(episode_id))
        manifest_archetypes[archetype] += 1
    if (
        len(manifest_ids) != contract.validation_episode_count
        or s2_summary["opponent_archetype_episode_counts"]
        != dict(sorted(manifest_archetypes.items()))
    ):
        raise QualificationError(
            "paired validation archetype coverage differs from frozen manifest"
        )
    s1_counts = s1_summary["classification_counts"]
    s2_counts = s2_summary["classification_counts"]
    exploratory_counts = exploratory_summary["classification_counts"]
    s1_rate = s1_summary["episode_rates"]["EXPERT_DOMINATES"]
    s2_rate = s2_summary["episode_rates"]["EXPERT_DOMINATES"]
    transition_matrix: dict[str, dict[str, int]] = {
        before: {after: 0 for after in LABELS} for before in LABELS
    }
    transitions = Counter()
    for before, after in zip(s1_rows, primary_rows):
        stable_fields = (
            "episode_id",
            "replay_sha256",
            "seat",
            "step",
            "turn",
            "own_turn_ordinal",
            "expert_action",
            "expert_semantic",
            "actual_order",
            "hero_deck_family",
            "opponent_archetype",
        )
        if any(before.get(field) != after.get(field) for field in stable_fields):
            raise QualificationError("paired validation stable row identity mismatch")
        before_label = str(before.get("classification"))
        after_label = str(after.get("classification"))
        transition_matrix[before_label][after_label] += 1
        transitions["all_ed_exits"] += before_label == "EXPERT_DOMINATES" and after_label != "EXPERT_DOMINATES"
        transitions["ed_to_non_ed"] += before_label == "EXPERT_DOMINATES" and after_label in {"EQUIVALENT", "AGENT_DOMINATES"}
        transitions["non_ed_to_ed"] += before.get("classification") != "EXPERT_DOMINATES" and after.get("classification") == "EXPERT_DOMINATES"
    baseline_families = {family for row in s1_rows if (family := _failure_family(row))}
    candidate_families = {
        family for row in [*primary_rows, *exploratory_rows] if (family := _failure_family(row))
    }
    new_families = sorted(candidate_families - baseline_families)
    if (
        s1_counts["EXPERT_DOMINATES"] - s2_counts["EXPERT_DOMINATES"]
        != transitions["all_ed_exits"] - transitions["non_ed_to_ed"]
    ):
        raise QualificationError("paired expert-dominance transition algebra mismatch")
    baseline_failure_burden = sum(
        s1_counts[label] for label in ("INCOMPARABLE", "UNCERTIFIABLE")
    )
    candidate_failure_burden = sum(
        s2_counts[label] for label in ("INCOMPARABLE", "UNCERTIFIABLE")
    )
    gates = {
        "primary_expert_dominates_count_decreased": (
            s2_counts["EXPERT_DOMINATES"] < s1_counts["EXPERT_DOMINATES"]
        ),
        "primary_expert_dominates_episode_rate_decreased": s2_rate < s1_rate,
        "favorable_ed_exits_exceed_reverse_ed_entries": (
            transitions["ed_to_non_ed"] > transitions["non_ed_to_ed"]
        ),
        "zero_certified_exploratory_expert_dominates": (
            exploratory_counts["EXPERT_DOMINATES"] == 0
        ),
        "zero_certified_exploratory_incomparable": (
            exploratory_counts["INCOMPARABLE"] == 0
        ),
        "no_new_failure_family": not new_families,
        "primary_incomparable_uncertifiable_burden_not_increased": (
            candidate_failure_burden <= baseline_failure_burden
        ),
        "zero_candidate_policy_errors": candidate_policy_errors == 0,
    }
    if any(value is not True for value in gates.values()):
        raise QualificationError("paired validation qualification/safety rule failed")
    baseline_family_payload = _families_payload(sorted(baseline_families))
    candidate_family_payload = _families_payload(sorted(candidate_families))
    new_family_payload = _families_payload(new_families)
    stage5_contract_view = {
        "baseline": {
            "source": {
                "path": _relative(contract.s1_validation, contract.root, "S1 validation"),
                "sha256": _sha256(contract.s1_validation),
            },
            **s1_summary,
        },
        "candidate": {
            "source": {
                "path": _relative(contract.s2_validation, contract.root, "S2 validation"),
                "sha256": _sha256(contract.s2_validation),
            },
            **s2_summary,
        },
        "paired_record_ids": {
            "count": len(s1_ids),
            "sequence_sha256": _object_sha256(s1_ids),
            "exact_order_match": True,
        },
        "paired_transitions": {
            "ed_to_non_ed": transitions["ed_to_non_ed"],
            "non_ed_to_ed": transitions["non_ed_to_ed"],
            "matrix": transition_matrix,
            "ed_count_identity_verified": True,
            "ed_to_non_ed_definition": (
                "EXPERT_DOMINATES to EQUIVALENT or AGENT_DOMINATES only"
            ),
        },
        "exploratory_safety_veto": {
            **exploratory_summary,
            "efficacy_credit_permitted": False,
        },
        "failure_families": {
            "baseline": baseline_family_payload,
            "candidate": candidate_family_payload,
            "new": new_family_payload,
        },
        "decision": {"verdict": "PASS", "passed": True, "gates": gates},
    }
    return {
        "baseline": {
            "path": _relative(contract.s1_validation, contract.root, "S1 validation"),
            "sha256": _sha256(contract.s1_validation),
            "expert_dominates_count": s1_counts["EXPERT_DOMINATES"],
            "expert_dominates_episode_rate": s1_rate,
        },
        "candidate": {
            "path": _relative(contract.s2_validation, contract.root, "S2 validation"),
            "sha256": _sha256(contract.s2_validation),
            "expert_dominates_count": s2_counts["EXPERT_DOMINATES"],
            "expert_dominates_episode_rate": s2_rate,
        },
        "ordered_record_ids": {
            "count": len(s1_ids),
            "sha256": _object_sha256(s1_ids),
            "exact_match": True,
        },
        "transitions": {
            "ed_to_non_ed": transitions["ed_to_non_ed"],
            "non_ed_to_ed": transitions["non_ed_to_ed"],
            "all_ed_exits": transitions["all_ed_exits"],
            "matrix": transition_matrix,
            "definition": "favorable ED exits only",
        },
        "exploratory": {
            "record_count": len(exploratory_rows),
            "expert_dominates_count": exploratory_counts["EXPERT_DOMINATES"],
            "incomparable_count": exploratory_counts["INCOMPARABLE"],
        },
        "failure_families": {
            "baseline": baseline_family_payload,
            "candidate": candidate_family_payload,
            "new": new_family_payload,
        },
        "primary_incomparable_uncertifiable_burden": {
            "baseline": baseline_failure_burden,
            "candidate": candidate_failure_burden,
        },
        "candidate_policy_error_count": candidate_policy_errors,
        "gates": gates,
        "stage5_contract_view": stage5_contract_view,
    }


def build_qualification_payload(
    contract: QualificationContract,
    *,
    stage_recompute: Callable[[Path], Mapping[str, Any]] | None = None,
) -> dict[str, Any]:
    missing = _missing(contract)
    if missing:
        raise QualificationError("qualification pending; missing: " + "; ".join(missing))
    stages = _verify_stages(contract, recompute=stage_recompute)
    validation = _verify_validations(contract)
    if stages["stage5_contract_view"] != validation["stage5_contract_view"]:
        raise QualificationError(
            "cumulative Stage5 report differs from independent validation recomputation"
        )
    payload: dict[str, Any] = {
        "schema": SCHEMA,
        "status": "QUALIFIED",
        "candidate": "s2",
        "qualification_rule": RULE_VERSION,
        "baseline_s1_validation_sha256": contract.pins["s1_validation_sha256"],
        "candidate_validation": validation["candidate"],
        "candidate_package": {
            "archive_sha256": contract.pins["s2_archive_sha256"],
            "manifest_sha256": contract.pins["s2_manifest_sha256"],
            "extracted_tree_sha256": contract.pins["s2_extracted_tree_sha256"],
            "runtime_source_tree_sha256": contract.pins["s2_runtime_tree_sha256"],
        },
        "baseline_package": {
            "archive_sha256": contract.pins["s1_archive_sha256"],
            "manifest_sha256": contract.pins["s1_manifest_sha256"],
            "extracted_tree_sha256": contract.pins["s1_extracted_tree_sha256"],
            "runtime_source_tree_sha256": contract.pins["s1_runtime_tree_sha256"],
        },
        "evaluator": _provenance(contract.evaluator, contract.root),
        "creator": _provenance(contract.creator, contract.root),
        "replay_manifest": _verify_manifest(contract),
        "staged_evaluation": stages,
        "paired_record_contract": validation["ordered_record_ids"],
        "rules": {
            "version": RULE_VERSION,
            "all_stage1_through_stage5_verdicts_pass": True,
            "paired_primary_expert_dominates_count_and_rate_strictly_lower": True,
            "paired_primary_favorable_ed_exits_exceed_reverse": True,
            "paired_primary_incomparable_uncertifiable_burden_not_increased": True,
            "zero_candidate_policy_errors": True,
            "exploratory_certified_expert_dominates_and_incomparable_zero": True,
            "no_new_failure_family": True,
            "stage5_report_matches_independent_recomputation": True,
            "recomputed_validation": validation,
        },
    }
    payload["qualification_payload_sha256"] = _object_sha256(payload)
    return payload


def verify_qualification_file(
    path: str | Path,
    contract: QualificationContract,
    *,
    stage_recompute: Callable[[Path], Mapping[str, Any]] | None = None,
) -> dict[str, Any]:
    qualification = Path(path).resolve()
    if qualification != contract.output.resolve():
        raise QualificationError("qualification path is not canonical")
    if not qualification.is_file():
        raise QualificationError("qualification is absent; final holdout remains disabled")
    actual = _read_json(qualification, "qualification")
    claimed = str(actual.get("qualification_payload_sha256") or "").upper()
    unsigned = dict(actual)
    unsigned.pop("qualification_payload_sha256", None)
    if len(claimed) != 64 or _object_sha256(unsigned) != claimed:
        raise QualificationError("qualification payload digest mismatch")
    expected = build_qualification_payload(contract, stage_recompute=stage_recompute)
    if actual != expected:
        raise QualificationError("qualification differs from recomputed rules/pins")
    return {
        "schema": SCHEMA,
        "status": "QUALIFIED",
        "file_sha256": _sha256(qualification),
        "payload_sha256": claimed,
        "candidate_validation_sha256": expected["candidate_validation"]["sha256"],
        "rule_version": RULE_VERSION,
    }


def verify_canonical_qualification(path: str | Path = DEFAULT_OUTPUT) -> dict[str, Any]:
    return verify_qualification_file(path, canonical_contract())


def _exclusive_write(path: Path, payload: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    encoded = json.dumps(payload, indent=2, sort_keys=True).encode() + b"\n"
    try:
        descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    except FileExistsError as exc:
        raise QualificationError("canonical qualification already exists; write-once refusal") from exc
    with os.fdopen(descriptor, "wb") as handle:
        handle.write(encoded)
        handle.flush()
        os.fsync(handle.fileno())


def create_qualification(
    contract: QualificationContract,
    *,
    stage_recompute: Callable[[Path], Mapping[str, Any]] | None = None,
) -> dict[str, Any]:
    canonical = contract.root / "data/dipplin_replay_eval/frozen/s2_qualification.json"
    if contract.output.resolve() != canonical.resolve():
        raise QualificationError("qualification output is not the tracked canonical path")
    if contract.output.exists():
        raise QualificationError("canonical qualification already exists; write-once refusal")
    payload = build_qualification_payload(contract, stage_recompute=stage_recompute)
    _exclusive_write(contract.output, payload)
    return verify_qualification_file(
        contract.output, contract, stage_recompute=stage_recompute
    )


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args(argv)
    try:
        contract = canonical_contract()
        if args.output.resolve() != contract.output.resolve():
            raise QualificationError("--output must be the tracked canonical path")
        result = (
            verify_qualification_file(args.output, contract)
            if args.verify else create_qualification(contract)
        )
    except (OSError, QualificationError) as exc:
        print(f"S2 qualification failed closed: {exc}", file=sys.stderr)
        return 2
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
