#!/usr/bin/env python3
"""Build exactly one deterministic sterile archive for qualified damage V0."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from scripts.build_grim_damage_candidates import (  # noqa: E402
    DECK_SHA256,
    MODEL_SHA256,
    extract,
    install_damage_v0,
    sha256,
    tree_sha256,
    verify_base,
)
from scripts.build_recovery_probes import deterministic_tar, safe_extract  # noqa: E402


def build_stage(path: Path) -> dict:
    extract(path)
    verify_base(path)
    install_damage_v0(path)
    return {
        "tree_sha256": tree_sha256(path),
        "model_sha256": sha256(path / "policy_weights.npz"),
        "first_model_sha256": sha256(path / "policy_first.npz"),
        "second_model_sha256": sha256(path / "policy_second.npz"),
        "deck_sha256": sha256(path / "deck.csv"),
    }


def sterile_smoke(archive: Path) -> dict:
    with tempfile.TemporaryDirectory(prefix="grim-damage-sterile-") as directory:
        stage = Path(directory)
        safe_extract(archive, stage)
        code = f'''\
import hashlib, json, pathlib, sys
sys.path.insert(0, {str(stage)!r})
import main
deck = main.agent({{"select": None, "current": None, "logs": []}})
router = main._AGENT
digest = lambda name: hashlib.sha256(pathlib.Path(name).read_bytes()).hexdigest().upper()
assert len(deck) == 60
assert type(router).__name__ == "ActualOrderAgent"
assert router.actual_order is None
assert digest("deck.csv") == {DECK_SHA256!r}
assert digest("policy_weights.npz") == {MODEL_SHA256!r}
assert digest("policy_first.npz") == {MODEL_SHA256!r}
assert digest("policy_second.npz") == {MODEL_SHA256!r}
assert router.exact.policy.damage_solver.enabled is False
assert router.policy_first.policy.damage_solver.enabled is True
assert router.policy_second.policy.damage_solver.enabled is True
print(json.dumps({{"deck_card_count": len(deck), "router": type(router).__name__, "solver": "v0"}}))
'''
        environment = dict(os.environ)
        environment.pop("PYTHONPATH", None)
        environment.pop("PTCG_GRIM_DAMAGE_SOLVER", None)
        result = subprocess.run(
            [sys.executable, "-I", "-B", "-c", code], cwd=stage,
            env=environment, capture_output=True, text=True, timeout=60,
        )
        if result.returncode:
            raise RuntimeError(result.stderr.strip() or result.stdout.strip())
        if any(path.name == "__pycache__" or path.suffix == ".pyc" for path in stage.rglob("*")):
            raise RuntimeError("sterile smoke generated bytecode")
        return {
            "passed": True,
            "clean_extraction": True,
            "isolated_import": True,
            "bytecode_disabled": True,
            **json.loads(result.stdout.strip().splitlines()[-1]),
        }


def main() -> int:
    output = ROOT / "artifacts/grim_damage_conversion/winner"
    output.mkdir(parents=True, exist_ok=True)
    archive = output / "grim_a2_damage_v0.tar.gz"
    manifest_path = output / "grim_a2_damage_v0.manifest.json"
    extracted = output / "extracted"
    with tempfile.TemporaryDirectory(prefix="grim-damage-build-", dir=output) as directory:
        work = Path(directory)
        stages = [work / "stage_a", work / "stage_b"]
        metadata = [build_stage(stage) for stage in stages]
        if metadata[0] != metadata[1]:
            raise RuntimeError("fresh package stages differ")
        archives = [work / "a.tar.gz", work / "b.tar.gz"]
        for stage, candidate_archive in zip(stages, archives):
            deterministic_tar(stage, candidate_archive)
        archive_hashes = [sha256(path) for path in archives]
        if archive_hashes[0] != archive_hashes[1]:
            raise RuntimeError(f"deterministic double build mismatch: {archive_hashes}")
        smoke = sterile_smoke(archives[0])
        shutil.copyfile(archives[0], archive)

    if extracted.exists():
        shutil.rmtree(extracted)
    extracted.mkdir()
    safe_extract(archive, extracted)
    manifest = {
        "status": "qualified_winner_packaged_not_uploaded",
        "archive": str(archive.resolve()),
        "archive_sha256": sha256(archive),
        "archive_bytes": archive.stat().st_size,
        "extracted": str(extracted.resolve()),
        "extracted_tree_sha256": tree_sha256(extracted),
        "deterministic_double_build": True,
        "model_sha256": MODEL_SHA256,
        "deck_sha256": DECK_SHA256,
        "stage": metadata[0],
        "sterile_smoke": smoke,
        "uploaded": False,
    }
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    print(json.dumps(manifest, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
